### ISSUE TITLE
H2D left and right nozzle information will not be displayed separately

### ISSUE THREAD

**Issue by AnalogKnight** [greghesp/ha-bambulab#1238]
This add-on worked fine on H2D and most of the information was able to be displayed.
However, it doesn't seem to be able to differentiate between the left and right nozzles, and it looks like it only displays information for the right nozzle. The external spool also seems to only have the right side available.
Are there any updates planned for this?

**Comment by AdrianGarside** [comment]
Please provide a diagnostics dump.

**Comment by AnalogKnight** [comment]
Thanks for your response, I hope this is the required file:

[config_entry-bambu_lab-01JS3XQ0SN4KQPHKG2NK8QCT3B.json](https://github.com/user-attachments/files/19933880/config_entry-bambu_lab-01JS3XQ0SN4KQPHKG2NK8QCT3B.json)

**Comment by AnalogKnight** [comment]
Hi, it seems to always show the info for the right nozzle. When the left nozzle is working, the nozzle temperature shown in the plugin is still the same as the right nozzle all the time, and I can see that it stops heating up and gradually cools down.
The contents of the Bambu Handy are shown in the picture, it will display information about each of the two nozzles. If you want, I can take screenshot again after switching the interface language to English.

![Image](https://github.com/user-attachments/assets/8f09cab3-a730-4742-9eef-c73f1fc94491)

**Comment by AnalogKnight** [comment]
Sure, I hope this will be helpful:

![Image](https://github.com/user-attachments/assets/f84512fd-aa31-45e8-94ea-8432eca79092)

[config_entry-bambu_lab-01JS3XQ0SN4KQPHKG2NK8QCT3B (2).json](https://github.com/user-attachments/files/19945247/config_entry-bambu_lab-01JS3XQ0SN4KQPHKG2NK8QCT3B.2.json)

**Comment by AdrianGarside** [comment]
Target temperature is "temp" in this extruder section / 65536:
```
        "extruder": {
          "info": [
            {
              "filam_bak": [
                12
              ],
              "hnow": 0,
              "hpre": 0,
              "htar": 0,
              "id": 0,
              "info": 75,
              "snow": 65280,
              "spre": 65280,
              "star": 65280,
              "stat": 197376,
              "temp": 14418140 // 220
            },
            {
              "filam_bak": [],
              "hnow": 1,
              "hpre": 1,
              "htar": 1,
              "id": 1,
              "info": 110,
              "snow": 769,
              "spre": 769,
              "star": 769,
              "stat": 196608,
              "temp": 5767327 // 88
            }
          ],
          "state": 2
        },
```

Whereas the data the integration currently looks for just has the data for the left nozzle:
```
      "nozzle_diameter": "0.4",
      "nozzle_target_temper": 88.0,
      "nozzle_temper": 159.0,
```

But you said 'it looks like it only displays information for the right nozzle'? Which isn't matching what I see in the logs you provide vs the screenshot.

**Comment by AdrianGarside** [comment]
A video might be useful. Could you also grab two diagnostics logs for the same print - one when each nozzle is active?

And does the active nozzle _ever_ show different values here:
![Image](https://github.com/user-attachments/assets/605aee0b-1ea0-456d-b25b-1fbae4276b73)
Or is the value shown for the active nozzle always the same two numbers?

**Comment by AdrianGarside** [comment]
Actually I have worked it out:
```
        "extruder": {
          "info": [
            {
...
              "temp": 14418140 // 220 in high word, 220 in low word
            },
            {
...
              "temp": 5767327 // 88 in high word, 159 in low word
            }
``

**Comment by AnalogKnight** [comment]
Thank you for your work. I downloaded the two files as you requested, hope this helps.

[right.json](https://github.com/user-attachments/files/19978310/right.json)
[left.json](https://github.com/user-attachments/files/19978311/left.json)

**Comment by AdrianGarside** [comment]
Still not clear to me how it tracks the active nozzle. Does Bambu Studio show the active nozzle state? I'm looking at the source now to see if I can locate anything that does that but so far I only see code to display the current/target temperatures and set the nozzle icon to 'active' if the target temperatures is >= 2 degrees higher than the current temperature which isn't the same.

**Comment by AnalogKnight** [comment]
Is that what you are referring to? Bambu Studio also displays information for both nozzles.

![Image](https://github.com/user-attachments/assets/96eaa015-aa64-4f07-890e-d35961974280)

**Comment by AdrianGarside** [comment]
Yes. So the code must be there to determine which nozzle is active. I’ll keep looking.

**Comment by AdrianGarside** [comment]
Ok, this seems to be it and was the 'State' integer I'd been assuming it must be.

            json const& extruder = device["extruder"];

            auto extder_data = ExtderData();
            extder_data.total_extder_count        = get_flag_bits(extruder["state"].get<int>(), 0, 4);

            extder_data.current_extder_id         = get_flag_bits(extruder["state"].get<int>(), 4, 4);
            extder_data.target_extder_id          = get_flag_bits(extruder["state"].get<int>(), 8, 4);
            extder_data.switch_extder_state       = (ExtruderSwitchState) get_flag_bits(extruder["state"].get<int>(), 12, 3);
            extder_data.current_loading_extder_id = get_flag_bits(extruder["state"].get<int>(), 15, 4);
            extder_data.current_busy_for_loading  = get_flag_bits(extruder["state"].get<int>(), 19);

Your left State == 33042 (1000 0001 0001 0010
Your right State == 2      (0000 0000 0000 0010)

Per the above, in your provided logs:
Bottom 4 bits = count of extruders == 2
Next 4 bits are the current extruder. So left == 0001 and right == 0000
Next 4 bits are target extruder. Also left == 0001 and right == 0000
Not sure what the difference between current and target is. But current seems to be what we want.
Next 3 bits are the ExtruderSwitchState. Not set for either:
enum ExtruderSwitchState {
    ES_IDLE = 0,
    ES_BUSY,
    ES_SWITCHING,
    ES_SWITCHING_FAILED
};
Next 4 bits are for which extruder is loading
Final bit is if it's busy and can't load? Not extruder specific.

**Comment by AnalogKnight** [comment]
Glad to hear this is progressing. Is there any other information I can provide?

**Comment by AdrianGarside** [comment]
No, I think I have everything I need. I just need to find some time to work on this. Work got super hectic recently.

**Comment by AdrianGarside** [comment]
Please try this out:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.1.16-beta1

Expected changes:
- The existing sensors now show the active nozzle, not the inactive one (for compatibility with current carsds).
- There are now 4 new sensors for the H2D - current and target temperatures for each of left and right.
- Number controls are not yet hooked up - these would only work in developer lab mode anyway and the H2D doesn't have that currently.

**Comment by AnalogKnight** [comment]
Thanks for the update.
Unfortunately, things seem to be getting worse, and although there are 4 new sensors, none of them are showing the correct values.
Also most of the other sensor values have become unavailable or clearly unreasonable, and my printer chamber temperature looks like it's trying to generate nuclear fusion.

![Image](https://github.com/user-attachments/assets/82180d1b-b34d-4d28-bd6f-69fb66621513)

![Image](https://github.com/user-attachments/assets/d4b2c3e1-220e-4cb4-9ded-a15846c968dc)

**Comment by AdrianGarside** [comment]
What values are the left/right nozzles saying in that screenshot?

The H2D has active chamber heating?

**Comment by AdrianGarside** [comment]
![Image](https://github.com/user-attachments/assets/d68f3368-a4ea-4ffd-8658-6be752c08293)

**Comment by AdrianGarside** [comment]
Looks like I need to account for active heating on the chamber temp:
2949164 = 0x2D 002C 
Target temp = 45
Current temp = 44

**Comment by AnalogKnight** [comment]
Hello, I'm not sure if this is the error log you are referring to. Please let me know if I am mistaken.

[home-assistant_bambu_lab_2025-05-15T02-56-08.129Z.log.zip](https://github.com/user-attachments/files/20224227/home-assistant_bambu_lab_2025-05-15T02-56-08.129Z.log.zip)

**Comment by AnalogKnight** [comment]
I apologize for the inconvenience, I'll set the language to English before take screenshot afterward.

**Comment by AdrianGarside** [comment]
Thanks. That pointed me at the immediate mistake and I have fixed that in this drop:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.1.16-beta2

There is a second error that I don't see an obvious cause for. It's possibly a side effect of the first but I'd like to know if you continue to see that with the fixed version:
```
2025-05-14 16:37:38.432 ERROR (H2D-Mqtt-122) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
Traceback (most recent call last):
  File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 600, in on_message
    self._device.print_update(data=json_data.get("print"))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/pybambu/models.py", line 99, in print_update
    send_event = send_event | self.ams.print_update(data = data)
                              ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/pybambu/models.py", line 2005, in print_update
    if self.data[index] is None:
       ~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

**Comment by AnalogKnight** [comment]
Hi, it looks like most of the sensors are back to working order. Unfortunately the nozzle temp and chamber temp still don't display properly.
In addition to this the camera no longer displays and the nozzle always seems to show as stainless steel (it's actually hardened steel).

**Comment by AdrianGarside** [comment]
Looks like you have an AMS HT attached from the errors in your log. This should be fixed in the latest 2.1.16 release. Please open a new issue if you are still seeing issues.

**Comment by AdrianGarside** [comment]
Please give this a go:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.1.19-alpha2

**Comment by AnalogKnight** [comment]
Thanks for the great work, all the temperature info has been displayed correctly.
However, there may still be a couple of issues. Build plate is always shown as smooth pei/high temp. The nozzle diameter is shown as 0mm and the nozzle type is still always stainless steel.

**Comment by AdrianGarside** [comment]
Can you add a new diagnostics log? In your original one the nozzle is being listed as stainless:
      "nozzle_type": "stainless_steel",

But nozzle diameter is in the payload in the existing form so I don't see how that would be mishandled:
      "nozzle_diameter": "0.4",

And it does look like they have completely changed how the plate is reported so that existing code won't work. Although that should mean it's showing 'unknown', so that's odd.

**Comment by AdrianGarside** [comment]
Can you open this as a new issue with the above information please?
