### ISSUE TITLE
[Feature] PETG-HF support

### ISSUE THREAD

**Issue by Kirbo** [greghesp/ha-bambulab#567]
### Describe the feature

Current implementation does not recognize new Bambu Lab PETG-HF filament.

https://eu.store.bambulab.com/en-fi/products/petg-hf

![image](https://github.com/user-attachments/assets/8fb26f97-e5d6-4f2a-b058-a3f79871f246)

```
Active                   false
Empty                    false
Color                    #000000FF
Name                     unknown
Nozzle min temperature   230
Nozzle max temperature   260
Remaining filament       75
Spool serial number      4AEEFD7000000100
Type                     PETG
```

### What device is this for?

AMS

**Comment by Kirbo** [comment]
> Stale issue message

Apparently waiting for https://github.com/greghesp/ha-bambulab/pull/556 to be merged.

**Comment by AdrianGarside** [comment]
Should be fixed now.

**Comment by Kirbo** [comment]
Still not working.

Bambu Studio filament selector
![image](https://github.com/user-attachments/assets/a966faea-9f39-44c8-963c-66671aecdbd2)

This one has PETG-HF
![image](https://github.com/user-attachments/assets/e78f65dd-a40e-4639-bc8c-35ebef2d6295)

Card of the whole AMS
![image](https://github.com/user-attachments/assets/ec57d020-f4ae-4443-90bb-d1f031dc279b)

**Comment by AdrianGarside** [comment]
Are you running the latest dev version? I think the fix isn't in the non-dev releases yet.

**Comment by Kirbo** [comment]
Ah, well that might be the case, so I'll just wait until it gets deployed out in the wild.
I'm running v2.0.22.

**Comment by Kirbo** [comment]
Seems to be working now, as the update got released! 🙂
