### ISSUE TITLE
[Bug] <Bambu Lap P1P sends no Update Information to HA>

### ISSUE THREAD

**Issue by mariofuhr** [greghesp/ha-bambulab#613]
### Describe the bug

After the firmware update to version 01.06.01.02 the printer no longer sends data to Home Assistant

### To Reproduce

Upgrade P1P to Firmware Version 01.06.01.02

### Expected Behaviour

Data has to Send to Home Assistant

### What device are you using?

P1P

### Diagnostic Output

```shell
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.10.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.6.31-haos-raspi",
    "supervisor": "2024.10.2",
    "host_os": "Home Assistant OS 13.2",
    "docker_version": "27.2.0",
    "chassis": "embedded",
    "run_as_root": true
  
  },
    "bambu_lab": {
      "documentation": "https://github.com/greghesp/ha-bambulab",
      "version": "2.0.22",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "bambu_lab",
    "name": "Bambu Lab",
    "codeowners": [
      "greghesp",
      "AdrianGarside"
    ],
    "config_flow": true,
    "dependencies": [
      "device_automation",
      "ffmpeg",
      "mqtt"
    ],
    "documentation": "https://github.com/greghesp/ha-bambulab",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/greghesp/ha-bambulab/issues",
    "ssdp": [
      {
        "st": "urn:bambulab-com:device:3dprinter:1"
      }
    ],
    "version": "2.0.22",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 4.0723010897636414e-05
    },
    "4b2326ac00fd6161d38676df1e375ef8": {
      "wait_import_platforms": -0.10337930399691686,
      "wait_base_component": -0.001533555012429133,
      "config_entry_setup": 0.12522522802464664
    }
  },
  "data": {
    "config_entry": {
      "created_at": "1970-01-01T00:00:00+00:00",
      "data": {
        "device_type": "P1P",
        "serial": "**REDACTED**"
      },
      "discovery_keys": {},
      "disabled_by": null,
      "domain": "bambu_lab",
      "entry_id": "4b2326ac00fd6161d38676df1e375ef8",
      "minor_version": 1,
      "modified_at": "2024-10-21T12:52:07.091353+00:00",
      "options": {
        "region": "",
        "email": "",
        "username": "",
        "name": "",
        "host": "172.16.101.35",
        "local_mqtt": true,
        "auth_token": "",
        "access_code": "**REDACTED**",
        "usage_hours": 154.34000000000003,
        "manual_refresh_mode": false
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "**REDACTED**",
      "unique_id": null,
      "version": 2
    },
    "push_all": null,
    "get_version": null
  }
}
```

**Comment by Macualey3** [comment]
got the same problem. is there a way to downgrade firmware?

**Comment by JamieEC** [comment]
Same issue here I assume

**Comment by Macualey3** [comment]
just downgraded to 01.06.01.00 but it's still not working. trying 01.06.00.00 now.

**Comment by Menthe11** [comment]
I have the same problem. After a print, the printer suddenly doesnt send data to the Integration. 
Did Firmware Update, still the same.

**Comment by lloydbayley** [comment]
Same here on the P1S in cloud mode. I am wondering if something has changed with the MQTT connection credentials....

**Comment by JamieEC** [comment]
I had very similar issues last week when I lost IPv6 connectivity; I wonder if Bambu has changed something on their side re. cloud connectivity?

**Comment by Menthe11** [comment]
Maybe some sort of expired certificate?

**Comment by pilo1337** [comment]
Should be the same as issue #612 , which should be fixed with #614

**Comment by RealDeco** [comment]
bambu lab went down yesterday morning and the problem with non updating entities happened right after, coincidence?, tried reconfiguring and it works fine (no error) but still not updating anything.. LAN mode configuration.

**Comment by AdrianGarside** [comment]
Almost certainly a dupe of #612

**Comment by lloydbayley** [comment]
Hooray for PR #614 !!! <party emoji which I don't know how to do>
