### ISSUE TITLE
[Bug] Cloudflare is blocking login attempts again

### ISSUE THREAD

**Issue by AdrianGarside** [greghesp/ha-bambulab#692]
### Describe the bug

2024-11-06 08:05:41.997 ERROR (SyncWorker_40) [custom_components.bambu_lab.pybambu] Login attempt failed with error code: 403
2024-11-06 08:05:41.997 DEBUG (SyncWorker_40) [custom_components.bambu_lab.pybambu] Response: <!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>

### To Reproduce

2024-11-06 08:05:41.997 ERROR (SyncWorker_40) [custom_components.bambu_lab.pybambu] Login attempt failed with error code: 403
2024-11-06 08:05:41.997 DEBUG (SyncWorker_40) [custom_components.bambu_lab.pybambu] Response: <!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>

### Expected Behaviour

Success

### What device are you using?

A1

### Diagnostic Output

```shell
2024-11-06 08:05:41.997 ERROR (SyncWorker_40) [custom_components.bambu_lab.pybambu] Login attempt failed with error code: 403
2024-11-06 08:05:41.997 DEBUG (SyncWorker_40) [custom_components.bambu_lab.pybambu] Response: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
```

**Comment by AdrianGarside** [comment]
Looking at the new code, it seems that for non-China login attempts the first connection attempt with password is pointless - it is now always going to be told to use the one-time verification code (auto-sent). Instead we can just go directly to requesting that code. However with the prior test app that @t0nyz0 created the login attempt with code is also being cloudflared.

**Comment by t0nyz0** [comment]
I think I know what they fixed @AdrianGarside 
I'll make some adjustments to my script and see if I can get it working again.

**Comment by t0nyz0** [comment]
@AdrianGarside well.. good news and bad news. Bad news, cloudflare does make it harder. Good news, its not impossible but will require extra libraries. I think they also butterfingered the tfa endpoint the first release, they fixed it in this release which completely changes the endpoint. I expected this. 

See my fix here:
https://github.com/t0nyz0/bambu-auth/blob/main/auth.py

**Comment by AdrianGarside** [comment]
I’d seen the various posts on using cloudscraper to workaround cloudflare. What does it do differently that requests/httpx don’t do?

**Comment by t0nyz0** [comment]
@AdrianGarside funny enough I was just asking myself that same question. It does a lot, automated handling of the cloudflare challenges ("please wait five seconds...") this one is particularly annoying. Also does browser emulation, rotating user-agents and even solve captchas if you want.

**Comment by AdrianGarside** [comment]
I am kind of confused how they can cloudflare a REST api with those kind of behaviors. What do the Bambu apps do to handle things like that?

**Comment by t0nyz0** [comment]
So the way I understand it is, the bambu iPhone app & Makerworld website use the [login HTML form](https://bambulab.com/en/sign-in) for authentication. When I select 'login' in the app or website, the html form loads, and during this process, Cloudflare’s verification completes in the background automatically. After logging in, an access token is issued for API communications. This token relies on the cached **Cloudflare validation tokens granted during login**, meaning Cloudflare’s initial security check is retained for subsequent API requests without requiring repeated verification. As a result, Cloudflare’s protection does not disrupt the Bambu app’s operation. But my understanding might not be 100% accurate, just based on observations and guesses.

**Comment by AdrianGarside** [comment]
Should be fixed with #698

**Comment by AdrianGarside** [comment]
@t0nyz0 what does this do?

```verify=certifi.where()```

I didn't add it when I switched to cloudscraper since it wasn't needed.

**Comment by rebelthor** [comment]
@AdrianGarside Looks like #698 wasn't enough as we're still unable to login, see #732
