### ISSUE TITLE
[Bug] P1S in LAN Only mode, blank camera + Configure no longer functions

### ISSUE THREAD

**Issue by cryptonym64** [greghesp/ha-bambulab#878]
### Home Assistant Version

2025.1.5

### Bambu Lab Integration Version

2.0.41

### Describe the bug

The camera stopped working when this version was applied. Says streaming, but window is black.  I saw in notes work was done for IP address from MQTT. Looking at my device attributes, the IP Address field in HA is blank. So if it's substituting the blank over the one in the config, that would explain this. 

While checking settings, printer confirmed on original IP, I clicked the Configure button and when I save I now get "Failed to connect. Check provided settings." even though all the values (IP, code, hours) are correct. 

I restored a backup and camera is back and Configure button works. 

I believe the new address logic is breaking things perhaps.

### To Reproduce

Install update.
Go to devices and pick integration and then device.
Camera is black.
Go to integration, click configure button.
Fields are prefilled, verify, save. 
Failure message.

### Expected Behaviour

Camera and config should use the supplied IP if the MQTT IP is blank, or logically, in LAN only mode use the static address in the config.

### What device are you using?

P1S

### Diagnostic Output

```shell
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2025.1.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.13.1",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/New_York",
    "os_name": "Linux",
    "os_version": "6.6.73-haos",
    "supervisor": "2024.12.3",
    "host_os": "Home Assistant OS 14.2",
    "docker_version": "27.2.0",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "proxmoxve": {
      "documentation": "https://github.com/dougiteixeira/proxmoxve",
      "version": "3.5.2",
      "requirements": [
        "proxmoxer==2.0.1"
      ]
    },
    "fontawesome": {
      "documentation": "https://github.com/thomasloven/hass-fontawesome",
      "version": "2.2.3",
      "requirements": []
    },
    "spook_inverse": {
      "documentation": "https://spook.boo",
      "version": "3.1.0",
      "requirements": []
    },
    "envisalink_new": {
      "documentation": "https://github.com/ufodone/envisalink_new",
      "version": "0.9.5",
      "requirements": []
    },
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.6.5",
      "requirements": [
        "prettytable==3.12.0"
      ]
    },
    "bambu_lab": {
      "documentation": "https://github.com/greghesp/ha-bambulab",
      "version": "2.0.41",
      "requirements": [
        "cloudscraper"
      ]
    },
    "spook": {
      "documentation": "https://spook.boo",
      "version": "3.1.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "bambu_lab",
    "name": "Bambu Lab",
    "codeowners": [
      "greghesp",
      "AdrianGarside"
    ],
    "config_flow": true,
    "dependencies": [
      "device_automation",
      "ffmpeg",
      "mqtt"
    ],
    "documentation": "https://github.com/greghesp/ha-bambulab",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/greghesp/ha-bambulab/issues",
    "requirements": [
      "cloudscraper"
    ],
    "ssdp": [
      {
        "st": "urn:bambulab-com:device:3dprinter:1"
      }
    ],
    "version": "2.0.41",
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 1.0303047019988298e-05
    },
    "01JJ0WYGRZ75HYA04HGEYC1WYC": {
      "wait_import_platforms": -0.06529130699345842,
      "wait_base_component": -0.0006452469970099628,
      "config_entry_setup": 0.0740541520062834,
      "config_entry_platform_setup": 0.007730431039817631
    }
  },
  "data": {
    "config_entry": {
      "created_at": "2025-01-20T03:43:51.583192+00:00",
      "data": {
        "device_type": "P1S",
        "serial": "**REDACTED**"
      },
      "discovery_keys": {},
      "disabled_by": null,
      "domain": "bambu_lab",
      "entry_id": "01JJ0WYGRZ75HYA04HGEYC1WYC",
      "minor_version": 1,
      "modified_at": "2025-01-27T17:15:19.145801+00:00",
      "options": {
        "access_code": "**REDACTED**",
        "auth_token": "",
        "email": "",
        "host": "192.168.1.88",
        "local_mqtt": true,
        "name": "",
        "region": "",
        "usage_hours": 1270.6599999999999,
        "username": ""
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "**REDACTED**",
      "unique_id": null,
      "version": 2
    },
    "push_all": {
      "upgrade_state": {
        "sequence_id": 0,
        "progress": "",
        "status": "",
        "consistency_request": false,
        "dis_state": 0,
        "err_code": 0,
        "force_upgrade": false,
        "message": "0%, 0B/s",
        "module": "",
        "new_version_state": 0,
        "cur_state_code": 0,
        "new_ver_list": []
      },
      "ipcam": {
        "ipcam_dev": "1",
        "ipcam_record": "enable",
        "timelapse": "disable",
        "resolution": "",
        "tutk_server": "disable",
        "mode_bits": 3
      },
      "upload": {
        "status": "idle",
        "progress": 0,
        "message": ""
      },
      "nozzle_temper": 28.90625,
      "nozzle_target_temper": 0,
      "bed_temper": 24.875,
      "bed_target_temper": 0,
      "chamber_temper": 5,
      "mc_print_stage": "1",
      "heatbreak_fan_speed": "0",
      "cooling_fan_speed": "0",
      "big_fan1_speed": "0",
      "big_fan2_speed": "0",
      "mc_percent": 0,
      "mc_remaining_time": 0,
      "ams_status": 0,
      "ams_rfid_status": 0,
      "hw_switch_state": 0,
      "spd_mag": 100,
      "spd_lvl": 2,
      "print_error": 83935249,
      "lifecycle": "product",
      "wifi_signal": "-70dBm",
      "gcode_state": "IDLE",
      "gcode_file_prepare_percent": "0",
      "queue_number": 0,
      "queue_total": 0,
      "queue_est": 0,
      "queue_sts": 0,
      "project_id": "0",
      "profile_id": "0",
      "task_id": "0",
      "subtask_id": "0",
      "subtask_name": "",
      "gcode_file": "",
      "stg": [],
      "stg_cur": 0,
      "print_type": "idle",
      "home_flag": 23086736,
      "mc_print_line_number": "0",
      "mc_print_sub_stage": 0,
      "sdcard": true,
      "force_upgrade": false,
      "mess_production_state": "active",
      "layer_num": 0,
      "total_layer_num": 0,
      "s_obj": [],
      "filam_bak": [],
      "fan_gear": 0,
      "nozzle_diameter": "0.4",
      "nozzle_type": "hardened_steel",
      "cali_version": 0,
      "hms": [],
      "online": {
        "ahb": false,
        "rfid": false,
        "version": 1188674307
      },
      "ams": {
        "ams": [
          {
            "id": "0",
            "humidity": "5",
            "temp": "0.0",
            "tray": [
              {
                "id": "0"
              },
              {
                "id": "1",
                "remain": -1,
                "k": 0.019999999552965164,
                "n": 1,
                "cali_idx": -1,
                "tag_uid": "0000000000000000",
                "tray_id_name": "",
                "tray_info_idx": "GFG99",
                "tray_type": "PETG",
                "tray_sub_brands": "",
                "tray_color": "000000FF",
                "tray_weight": "0",
                "tray_diameter": "0.00",
                "tray_temp": "0",
                "tray_time": "0",
                "bed_temp_type": "0",
                "bed_temp": "0",
                "nozzle_temp_max": "270",
                "nozzle_temp_min": "220",
                "xcam_info": "000000000000000000000000",
                "tray_uuid": "00000000000000000000000000000000",
                "ctype": 0,
                "cols": [
                  "000000FF"
                ]
              },
              {
                "id": "2",
                "remain": 60,
                "k": 0.03999999910593033,
                "n": 1,
                "cali_idx": -1,
                "tag_uid": "9DD060F200000100",
                "tray_id_name": "G00-B9",
                "tray_info_idx": "GFG00",
                "tray_type": "PETG",
                "tray_sub_brands": "PETG Basic",
                "tray_color": "001489FF",
                "tray_weight": "1000",
                "tray_diameter": "1.75",
                "tray_temp": "65",
                "tray_time": "8",
                "bed_temp_type": "2",
                "bed_temp": "0",
                "nozzle_temp_max": "270",
                "nozzle_temp_min": "220",
                "xcam_info": "88138813E803E8030000003F",
                "tray_uuid": "4A4288DEEE304253A0C86F0FFB27B463",
                "ctype": 0,
                "cols": [
                  "001489FF"
                ]
              },
              {
                "id": "3",
                "remain": 50,
                "k": 0.03999999910593033,
                "n": 1,
                "cali_idx": -1,
                "tag_uid": "2C4FF43E00000100",
                "tray_id_name": "G00-K0",
                "tray_info_idx": "GFG00",
                "tray_type": "PETG",
                "tray_sub_brands": "PETG Basic",
                "tray_color": "000000FF",
                "tray_weight": "1000",
                "tray_diameter": "1.75",
                "tray_temp": "65",
                "tray_time": "8",
                "bed_temp_type": "2",
                "bed_temp": "70",
                "nozzle_temp_max": "270",
                "nozzle_temp_min": "220",
                "xcam_info": "803E803E2003E8033333333F",
                "tray_uuid": "FC5C7256B36D4B789FE62E89BA1DD53A",
                "ctype": 0,
                "cols": [
                  "000000FF"
                ]
              }
            ]
          },
          {
            "id": "1",
            "humidity": "5",
            "temp": "0.0",
            "tray": [
              {
                "id": "0",
                "remain": 19,
                "k": 0.03999999910593033,
                "n": 1,
                "cali_idx": -1,
                "tag_uid": "E073E42D00000100",
                "tray_id_name": "G00-R0",
                "tray_info_idx": "GFG00",
                "tray_type": "PETG",
                "tray_sub_brands": "PETG Basic",
                "tray_color": "D6001CFF",
                "tray_weight": "1000",
                "tray_diameter": "1.75",
                "tray_temp": "65",
                "tray_time": "8",
                "bed_temp_type": "2",
                "bed_temp": "0",
                "nozzle_temp_max": "270",
                "nozzle_temp_min": "220",
                "xcam_info": "88138813E803E8030000003F",
                "tray_uuid": "16322EB4A7E94209AACBC688321EB435",
                "ctype": 0,
                "cols": [
                  "D6001CFF"
                ]
              },
              {
                "id": "1",
                "remain": 46,
                "k": 0.03999999910593033,
                "n": 1,
                "cali_idx": -1,
                "tag_uid": "9C30905400000100",
                "tray_id_name": "G00-Y0",
                "tray_info_idx": "GFG00",
                "tray_type": "PETG",
                "tray_sub_brands": "PETG Basic",
                "tray_color": "FCE300FF",
                "tray_weight": "1000",
                "tray_diameter": "1.75",
                "tray_temp": "65",
                "tray_time": "8",
                "bed_temp_type": "2",
                "bed_temp": "70",
                "nozzle_temp_max": "270",
                "nozzle_temp_min": "220",
                "xcam_info": "AC0DD007E803E8033333333F",
                "tray_uuid": "1E68D8D7BE684014B201D04B10770F22",
                "ctype": 0,
                "cols": [
                  "FCE300FF"
                ]
              },
              {
                "id": "2",
                "remain": 72,
                "k": 0.03999999910593033,
                "n": 1,
                "cali_idx": -1,
                "tag_uid": "4CCEFC3E00000100",
                "tray_id_name": "G00-D0",
                "tray_info_idx": "GFG00",
                "tray_type": "PETG",
                "tray_sub_brands": "PETG Basic",
                "tray_color": "9EA2A2FF",
                "tray_weight": "1000",
                "tray_diameter": "1.75",
                "tray_temp": "65",
                "tray_time": "8",
                "bed_temp_type": "2",
                "bed_temp": "70",
                "nozzle_temp_max": "270",
                "nozzle_temp_min": "220",
                "xcam_info": "D007D007E803E8033333333F",
                "tray_uuid": "309839123AE9400DB590103A9C713873",
                "ctype": 0,
                "cols": [
                  "9EA2A2FF"
                ]
              },
              {
                "id": "3",
                "remain": 53,
                "k": 0.03999999910593033,
                "n": 1,
                "cali_idx": -1,
                "tag_uid": "3019992F00000100",
                "tray_id_name": "G00-G6",
                "tray_info_idx": "GFG00",
                "tray_type": "PETG",
                "tray_sub_brands": "PETG Basic",
                "tray_color": "009639FF",
                "tray_weight": "1000",
                "tray_diameter": "1.75",
                "tray_temp": "65",
                "tray_time": "8",
                "bed_temp_type": "2",
                "bed_temp": "0",
                "nozzle_temp_max": "270",
                "nozzle_temp_min": "220",
                "xcam_info": "34218813E803E803CDCC4C3F",
                "tray_uuid": "208333F8B187443AB3856BDB6CCA90AE",
                "ctype": 0,
                "cols": [
                  "009639FF"
                ]
              }
            ]
          }
        ],
        "ams_exist_bits": "3",
        "tray_exist_bits": "fe",
        "tray_is_bbl_bits": "fe",
        "tray_tar": "255",
        "tray_now": "255",
        "tray_pre": "255",
        "tray_read_done_bits": "fe",
        "tray_reading_bits": "0",
        "version": 2,
        "insert_flag": true,
        "power_on_flag": false
      },
      "vt_tray": {
        "id": "254",
        "tag_uid": "0000000000000000",
        "tray_id_name": "",
        "tray_info_idx": "",
        "tray_type": "",
        "tray_sub_brands": "",
        "tray_color": "FFFFFFFF",
        "tray_weight": "0",
        "tray_diameter": "0.00",
        "tray_temp": "0",
        "tray_time": "0",
        "bed_temp_type": "0",
        "bed_temp": "0",
        "nozzle_temp_max": "0",
        "nozzle_temp_min": "0",
        "xcam_info": "000000000000000000000000",
        "tray_uuid": "00000000000000000000000000000000",
        "remain": 0,
        "k": 0.019999999552965164,
        "n": 1,
        "cali_idx": -1
      },
      "lights_report": [
        {
          "node": "chamber_light",
          "mode": "off"
        }
      ],
      "command": "push_status",
      "msg": 0,
      "sequence_id": "498"
    },
    "get_version": {
      "command": "get_version",
      "sequence_id": "0",
      "module": [
        {
          "name": "ota",
          "project_name": "C12",
          "sw_ver": "01.06.01.02",
          "hw_ver": "OTA",
          "sn": "**REDACTED**",
          "flag": 0
        },
        {
          "name": "esp32",
          "project_name": "C12",
          "sw_ver": "01.08.27.62",
          "hw_ver": "AP04",
          "sn": "**REDACTED**",
          "flag": 0
        },
        {
          "name": "mc",
          "project_name": "P1",
          "sw_ver": "00.00.26.61",
          "loader_ver": "00.00.00.23",
          "hw_ver": "MC07",
          "sn": "**REDACTED**",
          "flag": 0
        },
        {
          "name": "th",
          "project_name": "P1",
          "sw_ver": "00.00.09.95",
          "loader_ver": "00.00.00.14",
          "hw_ver": "TH09",
          "sn": "**REDACTED**",
          "flag": 0
        },
        {
          "name": "ams/0",
          "project_name": "",
          "sw_ver": "00.00.06.44",
          "loader_ver": "00.00.00.00",
          "ota_ver": "00.00.00.00",
          "hw_ver": "AMS08",
          "sn": "**REDACTED**",
          "flag": 0
        },
        {
          "name": "ams/1",
          "project_name": "",
          "sw_ver": "00.00.06.44",
          "loader_ver": "00.00.00.00",
          "ota_ver": "00.00.00.00",
          "hw_ver": "AMS08",
          "sn": "**REDACTED**",
          "flag": 0
        }
      ],
      "result": "success",
      "reason": ""
    }
  }
}
```

### Log Extracts

```shell

```

**Comment by lloydbayley** [comment]
Strange. I too, have a P1S but I use it in the normal cloud mode and I have lost all connectivity with the printer now.
Will report back after I roll the update back.

**Comment by Woodcat64** [comment]
Just confirming this bug. Also had to reload the integration few times to get all sensors working.

P1S in Lan mode, integration in local mode. Reverting to v2.0.40 fixes the problem.

**Comment by Lemonadel** [comment]
Same broken camera without LAN only mode but I am on FW 01.05.02 which is not streaming in Handy App but worked for past days in this addon up to this update. Will rollback to previous for sure.

**Comment by AdrianGarside** [comment]
Sorry about that. Will get a point fix out shortly.

**Comment by AdrianGarside** [comment]
Ah I see what happened. The IP address was only recently added so anyone running with an older firmware will be broken.

**Comment by AdrianGarside** [comment]
I can't test it but I believe this should fix it:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.42

**Comment by Lemonadel** [comment]
Sadly it’s not fixed for me. Without and with enabled “use image sensor camera”.
As on attached screens - entity seems to be missing but camera has status streaming. I have also clicked “Force refresh data”. 
Of course there was HA restart after update.

“MQTT connection mode” is Local if this counts, but again please keep in mind that this case is different as temporary I use non-local mode of printer but camera got hit by update :)

Added json diagnostics as well.

[config_entry-bambu_lab-6c906c0d92c4f006628ba8058a0a7cc4.json](https://github.com/user-attachments/files/18633321/config_entry-bambu_lab-6c906c0d92c4f006628ba8058a0a7cc4.json)

![Image](https://github.com/user-attachments/assets/6498c3f0-f9ff-466f-aaa0-adf5524cfd1d)
![Image](https://github.com/user-attachments/assets/0a615428-cffb-4f09-9e30-b5d5c28b3454)
![Image](https://github.com/user-attachments/assets/5dff88c0-7bb3-44bc-b3ac-df8d8ed1ae55)
![Image](https://github.com/user-attachments/assets/19ec6860-c0f6-4cef-a403-bb740c97babd)

**Comment by AdrianGarside** [comment]
Yeah, I just realized I screwed up and broke it for everyone. Another fix coming.

**Comment by Lemonadel** [comment]
Happens to the best :)

**Comment by AdrianGarside** [comment]
Take 2: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.43

**Comment by Lemonadel** [comment]
In my case of old HW + non-local mode, it’s back to work with .43

**Comment by oopiicaa** [comment]
Fixed for my A1 mini in LAN mode too👍

**Comment by ThatMattLatt** [comment]
Still not working on P1S + LAN-Mode, can't connect to the printer at all. Rolling back to 2.0.40 solves the issue for now.

**Comment by AdrianGarside** [comment]
> Still not working on P1S + LAN-Mode, can't connect to the printer at all. Rolling back to 2.0.40 solves the issue for now.

Can you enable debug logs and grab logs plus a diagnostic log?

**Comment by ThatMattLatt** [comment]
**Diagnostic logs**

```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.10.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.6.63-haos",
    "supervisor": "2024.12.3",
    "host_os": "Home Assistant OS 14.0",
    "docker_version": "27.2.0",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "fontawesome": {
      "documentation": "https://github.com/thomasloven/hass-fontawesome",
      "version": "2.2.3",
      "requirements": []
    },
    "spoolman": {
      "documentation": "https://github.com/Disane87/spoolman-homeassistant",
      "version": "0.0.0",
      "requirements": []
    },
    "auto_backup": {
      "documentation": "https://github.com/jcwillox/hass-auto-backup",
      "version": "1.5.1",
      "requirements": []
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "ics_calendar": {
      "documentation": "https://github.com/franc6/ics_calendar",
      "version": "5.0.5",
      "requirements": [
        "icalendar~=6.1",
        "python-dateutil>=2.9.0.post0",
        "pytz>=2024.1",
        "recurring_ical_events~=3.3,>=3.3.4",
        "ics>=0.7.2",
        "arrow",
        "httpx_auth>=0.22.0"
      ]
    },
    "home_connect_alt": {
      "documentation": "https://github.com/ekutner/home-connect-hass",
      "version": "1.1.12",
      "requirements": [
        "home-connect-async==0.8.0"
      ]
    },
    "dwd": {
      "documentation": "https://github.com/hg1337/homeassistant-dwd#readme",
      "version": "2024.9.0",
      "requirements": [
        "defusedxml==0.7.1"
      ]
    },
    "ui_lovelace_minimalist": {
      "documentation": "https://ui-lovelace-minimalist.github.io/UI/",
      "version": "v1.3.16",
      "requirements": [
        "aiofiles>=0.8.0",
        "aiogithubapi>=22.2.4"
      ]
    },
    "unraid": {
      "documentation": "https://github.com/domalab/ha-unraid/wiki",
      "version": "2025.01.08",
      "requirements": [
        "aiofiles>=23.2.1"
      ]
    },
    "roborock": {
      "documentation": "https://github.com/humbertogontijo/homeassistant-roborock",
      "version": "1.0.14",
      "requirements": [
        "python-roborock==0.40.0",
        "ical==7.0.3",
        "dacite==1.8.0"
      ]
    },
    "bambu_lab": {
      "documentation": "https://github.com/greghesp/ha-bambulab",
      "version": "2.0.43",
      "requirements": [
        "cloudscraper"
      ]
    },
    "gruenbeck_cloud": {
      "documentation": "https://github.com/p0l0/hagruenbeck_cloud",
      "version": "1.0.0b1",
      "requirements": [
        "pygruenbeck_cloud==1.0.0"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "documentation": "https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor",
      "version": "v2.2.3",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    }
  },
  "integration_manifest": {
    "domain": "bambu_lab",
    "name": "Bambu Lab",
    "codeowners": [
      "greghesp",
      "AdrianGarside"
    ],
    "config_flow": true,
    "dependencies": [
      "device_automation",
      "ffmpeg",
      "mqtt"
    ],
    "documentation": "https://github.com/greghesp/ha-bambulab",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/greghesp/ha-bambulab/issues",
    "requirements": [
      "cloudscraper"{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.10.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.6.63-haos",
    "supervisor": "2024.12.3",
    "host_os": "Home Assistant OS 14.0",
    "docker_version": "27.2.0",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "fontawesome": {
      "documentation": "https://github.com/thomasloven/hass-fontawesome",
      "version": "2.2.3",
      "requirements": []
    },
    "spoolman": {
      "documentation": "https://github.com/Disane87/spoolman-homeassistant",
      "version": "0.0.0",
      "requirements": []
    },
    "auto_backup": {
      "documentation": "https://github.com/jcwillox/hass-auto-backup",
      "version": "1.5.1",
      "requirements": []
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "ics_calendar": {
      "documentation": "https://github.com/franc6/ics_calendar",
      "version": "5.0.5",
      "requirements": [
        "icalendar~=6.1",
        "python-dateutil>=2.9.0.post0",
        "pytz>=2024.1",
        "recurring_ical_events~=3.3,>=3.3.4",
        "ics>=0.7.2",
        "arrow",
        "httpx_auth>=0.22.0"
      ]
    },
    "home_connect_alt": {
      "documentation": "https://github.com/ekutner/home-connect-hass",
      "version": "1.1.12",
      "requirements": [
        "home-connect-async==0.8.0"
      ]
    },
    "dwd": {
      "documentation": "https://github.com/hg1337/homeassistant-dwd#readme",
      "version": "2024.9.0",
      "requirements": [
        "defusedxml==0.7.1"
      ]
    },
    "ui_lovelace_minimalist": {
      "documentation": "https://ui-lovelace-minimalist.github.io/UI/",
      "version": "v1.3.16",
      "requirements": [
        "aiofiles>=0.8.0",
        "aiogithubapi>=22.2.4"
      ]
    },
    "unraid": {
      "documentation": "https://github.com/domalab/ha-unraid/wiki",
      "version": "2025.01.08",
      "requirements": [
        "aiofiles>=23.2.1"
      ]
    },
    "roborock": {
      "documentation": "https://github.com/humbertogontijo/homeassistant-roborock",
      "version": "1.0.14",
      "requirements": [
        "python-roborock==0.40.0",
        "ical==7.0.3",
        "dacite==1.8.0"
      ]
    },
    "bambu_lab": {
      "documentation": "https://github.com/greghesp/ha-bambulab",
      "version": "2.0.43",
      "requirements": [
        "cloudscraper"
      ]
    },
    "gruenbeck_cloud": {
      "documentation": "https://github.com/p0l0/hagruenbeck_cloud",
      "version": "1.0.0b1",
      "requirements": [
        "pygruenbeck_cloud==1.0.0"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "documentation": "https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor",
      "version": "v2.2.3",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    }
  },
  "integration_manifest": {
    "domain": "bambu_lab",
    "name": "Bambu Lab",
    "codeowners": [
      "greghesp",
      "AdrianGarside"
    ],
    "config_flow": true,
    "dependencies": [
      "device_automation",
      "ffmpeg",
      "mqtt"
    ],
    "documentation": "https://github.com/greghesp/ha-bambulab",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/greghesp/ha-bambulab/issues",
    "requirements": [
      "cloudscraper"
    ],
    "ssdp": [
      {
        "st": "urn:bambulab-com:device:3dprinter:1"
      }
    ],
    "version": "2.0.43",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 6.0688937082886696e-05
    },
    "1ead91ec383266f91fffa188c88b9fc1": {
      "wait_import_platforms": -1.5694190978538245,
      "wait_base_component": -0.030932983849197626,
      "config_entry_setup": 2.199534981045872
    }
  },
  "data": {
    "config_entry": {
      "created_at": "1970-01-01T00:00:00+00:00",
      "data": {
        "device_type": "P1S",
        "serial": "**REDACTED**"
      },
      "discovery_keys": {},
      "disabled_by": null,
      "domain": "bambu_lab",
      "entry_id": "1ead91ec383266f91fffa188c88b9fc1",
      "minor_version": 1,
      "modified_at": "2025-02-02T18:55:48.373101+00:00",
      "options": {
        "region": "Europe",
        "email": "**REDACTED**",
        "username": "**REDACTED**",
        "name": "Drucker",
        "host": "192.168.2.164",
        "local_mqtt": true,
        "auth_token": "**REDACTED**",
        "access_code": "**REDACTED**",
        "usage_hours": 1265.709999999999
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "**REDACTED**",
      "unique_id": null,
      "version": 2
    },
    "push_all": null,
    "get_version": null
  }
}
    ],
    "ssdp": [
      {
        "st": "urn:bambulab-com:device:3dprinter:1"
      }
    ],
    "version": "2.0.43",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 6.0688937082886696e-05
    },
    "1ead91ec383266f91fffa188c88b9fc1": {
      "wait_import_platforms": -1.5694190978538245,
      "wait_base_component": -0.030932983849197626,
      "config_entry_setup": 2.199534981045872
    }
  },
  "data": {
    "config_entry": {
      "created_at": "1970-01-01T00:00:00+00:00",
      "data": {
        "device_type": "P1S",
        "serial": "**REDACTED**"
      },
      "discovery_keys": {},
      "disabled_by": null,
      "domain": "bambu_lab",
      "entry_id": "1ead91ec383266f91fffa188c88b9fc1",
      "minor_version": 1,
      "modified_at": "2025-02-02T18:55:48.373101+00:00",
      "options": {
        "region": "Europe",
        "email": "**REDACTED**",
        "username": "**REDACTED**",
        "name": "Drucker",
        "host": "192.168.2.164",
        "local_mqtt": true,
        "auth_token": "**REDACTED**",
        "access_code": "**REDACTED**",
        "usage_hours": 1265.709999999999
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "**REDACTED**",
      "unique_id": null,
      "version": 2
    },
    "push_all": null,
    "get_version": null
  }
}
``` 

**Debug Log**

[home-assistant_bambu_lab_2025-02-02T19-43-44.613Z.log](https://github.com/user-attachments/files/18633629/home-assistant_bambu_lab_2025-02-02T19-43-44.613Z.log)

**Comment by AdrianGarside** [comment]
It's not clear what's going on from that. I see the connection to the printer is attempted without an obvious failure to connect. But the attempt to then send the requests for version info and a full data push are erroring out:
```
2025-02-02 20:40:28.854 DEBUG (MainThread) [custom_components.bambu_lab] Options Flow: Testing local mqtt Connection
2025-02-02 20:40:28.856 DEBUG (MainThread) [custom_components.bambu_lab.pybambu] Try Connection
2025-02-02 20:40:28.963 DEBUG (MainThread) [custom_components.bambu_lab.pybambu] Test connection: Connecting to 192.168.2.164
2025-02-02 20:40:31.138 DEBUG (P1S-Mqtt-67) [custom_components.bambu_lab.pybambu] Connect: Attempting Connection to 192.168.2.164
2025-02-02 20:40:32.026 DEBUG (MainThread) [custom_components.bambu_lab.pybambu]  Disconnect: Client Disconnecting
2025-02-02 20:40:37.036 DEBUG (P1S-Mqtt-67) [custom_components.bambu_lab.pybambu] Connect: Attempting Connection to 192.168.2.164
2025-02-02 20:40:37.464 ERROR (MainThread) [custom_components.bambu_lab.pybambu] Failed to send message to topic device/<SERIAL>/request
2025-02-02 20:40:37.465 ERROR (MainThread) [custom_components.bambu_lab.pybambu] Failed to send message to topic device/<SERIAL>/request
```
Can you double check the serial (I obfuscated it but it's in the log) and IP address are right?

**Comment by ThatMattLatt** [comment]
Removed the log due to obvious reasons.

Yes, the IP and the serial number are correct, the printer is the same and the IP is set to static.

**Comment by Woodcat64** [comment]
Upgrading to v2.0.43 seems to fix it for me. P1S fw 01.06.01.00

**Comment by AdrianGarside** [comment]
The log was incomplete. I think you only set it to debug in the UI which I've seen doesn't always give full debug logs. In your logs I'm only seeing debug output from the main HA thread and the MQTT thread but it's missing logging from some other threads. Can you try setting it to debug in the configuration.yaml file?

logger:
  default: info
  logs:
    custom_components.bambu_lab: debug

**Comment by AdrianGarside** [comment]
@ThatMattLatt can you open a separate issue for your connection problems. The camera issue was a specific regression that I caused with older firmware. Your issue is something else.
