### ISSUE TITLE
[Bug] Not all sensors are live updating

### ISSUE THREAD

**Issue by NicolasNID** [greghesp/ha-bambulab#92]
### Describe the bug

I have setup an automation in home assistant to turn of a aqara powerplug when the print status has changed from "running" to "finish". 
However i have noticed that this status is only updated after i open the bambu handy app (i haven't check the slicer yet). 
So now it has already happened several times that a print finishes overnight but the powerplug is not being switched off.

Is this a bug or am i missing something?

### To Reproduce

wait until a print finishes and check if the status changes.

### Expected Behaviour

should it not live update even without opening the app?

### What device are you using?

X1C

### Firmware Version

01.04.01.00

### Home Assistant Version

2023.4.0

### Component Version

1.0.2

**Comment by AdrianGarside** [comment]
I'm not able to repro this with my P1P with the latest alpha bits that I'm running and I don't know of any bugs that have been fixed that could explain it no longer reproing. 

When a print is done with my P1P:
![image](https://user-images.githubusercontent.com/26147576/231953075-8442d2e7-e7e6-4144-be77-d6ad9945ec18.png)

Print Status automatically changes from 'Running' to 'Idle'
Current Stage changes from 'Printing' to 'Unknown'

**Comment by Nicoautoxp** [comment]
I have update it to the latest version ans also did a re-install and reconnection of the printer. However it still doesn't live update.
I'm using the bambu cloud connection.
![Screenshot_20230414_203003_Gallery](https://user-images.githubusercontent.com/93649868/232128174-a7f03f20-5169-4982-871c-96b4f79095ac.jpg)
![Screenshot_20230414_203154_Gallery](https://user-images.githubusercontent.com/93649868/232128182-56d25757-bca9-49f9-aa38-989341cb551d.jpg)
![Screenshot_20230414_203044_Gallery](https://user-images.githubusercontent.com/93649868/232128184-1759129c-6441-4ac2-ad4a-70ee2d2a60a6.jpg)

**Comment by AdrianGarside** [comment]
There’s a report of similar problems with the node red integration on the home assistant forum although possibly P1P specific. I realized my setup of a separate test instance on my main PC that goes to sleep after 30 minutes would mean I trigger a fresh mqtt connection to the printer when my PC wakes from sleep. Which is apparently how it wakes the printer to start sending state updates again.

Your description of the behavior you observe seems pretty identical.

So I’m trying again to repro loss of live updates without that accidental corrective behavior in play.

**Comment by npike** [comment]
I've not noticed this with my P1P, updates to my long running homeassistant instance seem to always be timely (enough) to trigger audio notifications after a print is completed.

**Comment by AdrianGarside** [comment]
No repro for me leaving my P1P idle overnight. It's still receiving the regular wifi signal updates every ~second in the morning.

**Comment by NicolasNID** [comment]
i don't know what to say but i still have the issue. I've re-installed the addon serveral times and tried it out several time but still the same issue.
The home assistent sensors only update after i have opened the app. 
I've now connected to the the printer via node red and MQTT and will proceed that way.

**Comment by AdrianGarside** [comment]
Did you check the log output to see if anything relevant was showing?

**Comment by WolfwithSword** [comment]
Adding my two cents to this - it definitely seems like a P1P cloud limitation as I've seen a few people with the same issue as well. Local MQTT connections shouldn't have this issue - it's definitely the cloud sometimes getting "lazy" and needs the connection to be made alive again usually - local won't have the problem (and it does not mean the printer needs to be lan mode).

This is also the reason for semi-frequent mqtt disconnects - but as soon as *any* connection to the cloud mqtt server is re-established (from scratch) it works - whether it's studio, handy, or a third party integration.

**Comment by AdrianGarside** [comment]
Well until someone can reverse engineer what changed on the Bambu token login side, I’ve pulled the cloud mqtt support since it can’t connect successfully any more. Which also means I can’t test and mitigate the stalled connection.

**Comment by AdrianGarside** [comment]
Hit this today with my P1P with lan mqtt connection. The mqtt connection doesn't drop but we stop being fed any change data. I think I can mitigate by dropping and reconnecting the mqtt connection when in this state but it'll be hard to test without a reliable repro.

**Comment by WolfwithSword** [comment]
Could probably mitigate it by doing a reconnect on a timer if the model is a P1P, regardless of cloud or lan connection. Would need to make sure sensors don't go unavailable in between as to not break or affect some automations. 30 minutes as a random amount might be good enough to not affect any performance, but also less likely to risk connection drop.

Or for a probably better solution, store the time of when the last of any sensor updated. If it's been say 5-10m, attempt a reconnect. Not sure how fast the rate of P1P messages are when idle in a temperature controlled room though.

Initially I was thinking it could be mitigated by a push of a command on a timer, but I realized even in my nodered flows I have this (5m for versions and another for pushall) but I think users with P1Ps still had the issue (though it may have been cloud connection, not sure).

**Comment by AdrianGarside** [comment]
There's already a 'free' timer that we get when HA starts to poll us for data because we haven't told it anything changed. Generally it never triggers because the wifi level changes almost every second. It used to be set to a 10s poll timer and did occasionally trigger but I bumped it to 60s recently. With that change it should have virtually no chance of triggering if there isn't an actual problem with the mqtt connection. So I was thinking of using that to disconnect and reconnect the mqtt connection. But I'll need to be careful not to mess with the way an offline printer is handled. Although that puts bambu mqtt logic into the controller which I don't want to do so since it's knowledge the controller shouldn't have. Xo maybe I'll work out how to start a dedicated time from the mqtt handler instead.

**Comment by AdrianGarside** [comment]
I wonder if Bamby Studio or Handy is turning off the push:
    "pushing": {
        "sequence_id": "0",
        "command": "stop"
    }
}
That certainly puts things into the same state - mqtt connected but no longer receiving any updates. Can be restarted with a "start" command.

**Comment by WolfwithSword** [comment]
Weird, wonder why that's a thing. I guess a periodic sending of the "start" should resolve the issues then. Would love to figure out why it is, unless it's just performance / bogging down with messages related.

**Comment by AdrianGarside** [comment]
Yes, my machine got into this state - connected but not receiving any updates. Sending the start command restored it to expected behavior. So something is turning off the mqtt pushes - maybe as simple as a timer that bambu added, maybe something bambu studio/handy app is causing.

**Comment by WolfwithSword** [comment]
> Yes, my machine got into this state - connected but not receiving any updates. Sending the start command restored it to expected behavior. So something is turning off the mqtt pushes - maybe as simple as a timer that bambu added, maybe something bambu studio/handy app is causing.

Yeah, and I think with the direction the printer firmwares are going with syncing p1p and x1c quite a bit, I would probably think the start command should be periodically sent in any case. From testing on an X1C for past couple months, it has no harm even if all sensors send. And I was able to simulate the "lack" of sending by connecting to the cloud mqtt for a while - then it died off until I sent the same start command.

**Comment by AdrianGarside** [comment]
Fixed in https://github.com/greghesp/ha-bambulab/releases/tag/v1.4.4-dev
