### ISSUE TITLE
[Bug] Unable to add X1C (LAN Only Mode) via Lan Mode Connection

### ISSUE THREAD

**Issue by Signulled** [greghesp/ha-bambulab#924]
### Home Assistant Version

2025.1.4

### Bambu Lab Integration Version

v2.0.46

### Describe the bug

Error: Failed to connect. Check provided settings.

I've triple checked the IP Address, S/N, and Access Code. I've tried multiple times and rebooted Home Assistant. Orca Slicer is able to connect to the printer. I'm hoping it's just a dumb mistake on my end.

Printer Firmware Version: 01.07.05.00

### To Reproduce

1. Click "+ Add Integration"
2. Select Bambu Lab
3. Select "Lan Mode"
4. Enter the required information

### Expected Behaviour

The ability to add the integration and printer.

### What device are you using?

X1C

### Diagnostic Output

```shell
Unable to provide output as I cannot fully add the integration yet.
```

### Log Extracts

```shell

```

**Comment by MichaelCervoni** [comment]
I am having the same issue as well. I was able to add my printer to bambu studio with no issue using the same information. I am going to try the same with Orca.

**Comment by AdrianGarside** [comment]
This should be fixed in the 2.1.0 beta drop.

**Comment by pchandila** [comment]
Spent hours trying to debug this, thanks a lot for the fix.

**Comment by MichaelCervoni** [comment]
Might just be a me issue but I am still not able to get either of my printers to connect. I have tried v2.1.0-beta1, v2.1.0-beta4, v2.0.46-fix.

**Comment by AdrianGarside** [comment]
Please grab debug logs for the setup attempt. You'll need to turn debug logging for the integration on by adding this to your configuration.yaml and restarting the integration:
```
logger:
  default: info
  logs:
    custom_components.bambu_lab: debug
```
